//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiScaleExporter.MAUI.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppSnippets {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppSnippets() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiScaleExporter.MAUI.Resources.Localization.AppSnippets", typeof(AppSnippets).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This application is an open source community project and I have no affiliation with Garmin..
        /// </summary>
        internal static string AboutGarmin {
            get {
                return ResourceManager.GetString("AboutGarmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set the bluetooth address of the scale, and your data in the settings. Stand on your scale. Measure yourself. Mi Body Composition Scale is active up to 15 min after the measurement..
        /// </summary>
        internal static string AboutMeasureInstruction {
            get {
                return ResourceManager.GetString("AboutMeasureInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The application now supports MFA/2FA security features. If you save credentials in settings, authorization tokens will be remembered and you won&apos;t be asked every time for MFA code..
        /// </summary>
        internal static string AboutMFAAndStoringData {
            get {
                return ResourceManager.GetString("AboutMFAAndStoringData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Then you can review your data and upload it to Garmin Cloud. If you do not have Mi scale and just want to manually insert the data, you can so..
        /// </summary>
        internal static string AboutUpload {
            get {
                return ResourceManager.GetString("AboutUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alternate External API Address.
        /// </summary>
        internal static string AlternateExternalAPIAddress {
            get {
                return ResourceManager.GetString("AlternateExternalAPIAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App Settings.
        /// </summary>
        internal static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Basal Metabolism (kCal):.
        /// </summary>
        internal static string BasalMetabolosimKCal {
            get {
                return ResourceManager.GetString("BasalMetabolosimKCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bluetooth Address.
        /// </summary>
        internal static string BluetoothAddress {
            get {
                return ResourceManager.GetString("BluetoothAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bluetooth is disabled. Please enable Bluetooth to scan for your Mi Scale..
        /// </summary>
        internal static string BluetoothDisabled {
            get {
                return ResourceManager.GetString("BluetoothDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BMI.
        /// </summary>
        internal static string BMI {
            get {
                return ResourceManager.GetString("BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body age (years).
        /// </summary>
        internal static string BodyAgeYears {
            get {
                return ResourceManager.GetString("BodyAgeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body Fat (%).
        /// </summary>
        internal static string BodyFatPercent {
            get {
                return ResourceManager.GetString("BodyFatPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Body Type.
        /// </summary>
        internal static string BodyType {
            get {
                return ResourceManager.GetString("BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bone mass (Lbs).
        /// </summary>
        internal static string BoneMassLbs {
            get {
                return ResourceManager.GetString("BoneMassLbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bone mass (Kg).
        /// </summary>
        internal static string BoneMassPercent {
            get {
                return ResourceManager.GetString("BoneMassPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Buy me a coffee.
        /// </summary>
        internal static string BuyMeACoffee {
            get {
                return ResourceManager.GetString("BuyMeACoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel MFA Request.
        /// </summary>
        internal static string CancelMFARequest {
            get {
                return ResourceManager.GetString("CancelMFARequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel Search.
        /// </summary>
        internal static string CancelSearch {
            get {
                return ResourceManager.GetString("CancelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created by Lukasz Swiderski 2023.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data could not be obtained. try again.
        /// </summary>
        internal static string DataCouldNotBeObtained {
            get {
                return ResourceManager.GetString("DataCouldNotBeObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you like this app and would you like to support it?.
        /// </summary>
        internal static string DoYouLikeAndWouldYouLikeToSupport {
            get {
                return ResourceManager.GetString("DoYouLikeAndWouldYouLikeToSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Garmin Body Composition Form.
        /// </summary>
        internal static string GarminBodyCompositionForm {
            get {
                return ResourceManager.GetString("GarminBodyCompositionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Garmin Form.
        /// </summary>
        internal static string GarminForm {
            get {
                return ResourceManager.GetString("GarminForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Garmin Settings.
        /// </summary>
        internal static string GarminSettings {
            get {
                return ResourceManager.GetString("GarminSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate only .fit file.
        /// </summary>
        internal static string GenerateOnlyFitFile {
            get {
                return ResourceManager.GetString("GenerateOnlyFitFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Go to scan.
        /// </summary>
        internal static string GoToScan {
            get {
                return ResourceManager.GetString("GoToScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to write data..
        /// </summary>
        internal static string HealthConnectError {
            get {
                return ResourceManager.GetString("HealthConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Direct system integration with Health Connect is only available on Android 14 and higher..
        /// </summary>
        internal static string HealthConnectMinVersionError {
            get {
                return ResourceManager.GetString("HealthConnectMinVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Health Connect is only supported on Android..
        /// </summary>
        internal static string HealthConnectNotSupported {
            get {
                return ResourceManager.GetString("HealthConnectNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select MiScaleExporter and turn on the required toggles on the opened Health Connect settings screen..
        /// </summary>
        internal static string HealthConnectPermissionsMessage {
            get {
                return ResourceManager.GetString("HealthConnectPermissionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permissions Required.
        /// </summary>
        internal static string HealthConnectPermissionsTitle {
            get {
                return ResourceManager.GetString("HealthConnectPermissionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data successfully sent to Health Connect!.
        /// </summary>
        internal static string HealthConnectSuccess {
            get {
                return ResourceManager.GetString("HealthConnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8. Coffee.
        /// </summary>
        internal static string HelpCoffee {
            get {
                return ResourceManager.GetString("HelpCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Keep in mind that this is my hobby project. It was created for my inner needs and I believe it may be useful to others as well. I do not receive any compensation for creating and maintaining this project. If you want to support the development or thank me, you can buy me a coffee..
        /// </summary>
        internal static string HelpCoffeeDescription {
            get {
                return ResourceManager.GetString("HelpCoffeeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. How to connect to the scale.
        /// </summary>
        internal static string HelpConnect {
            get {
                return ResourceManager.GetString("HelpConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set the Bluetooth address of the scale in settings. Set the correct age/height/gender values. Measure yourself. The scale is active for up to 15 minutes after measurement..
        /// </summary>
        internal static string HelpConnectDescription {
            get {
                return ResourceManager.GetString("HelpConnectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bluetooth address can be found in Zepp Life &gt; Profile &gt; My devices &gt; Mi Body Composition Scale &gt; Bluetooth address (hold to copy).
        /// </summary>
        internal static string HelpConnectDescription2 {
            get {
                return ResourceManager.GetString("HelpConnectDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5. External Api.
        /// </summary>
        internal static string HelpExternalApi {
            get {
                return ResourceManager.GetString("HelpExternalApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на External API is used as a proxy for older Android phones (9 or lower). The default address is https://frog01-20364.wykr.es/. You can host your own version of the API and this app will send the data to your system instead of Garmin. Check out the project repository for more information..
        /// </summary>
        internal static string HelpExternalApiDescription {
            get {
                return ResourceManager.GetString("HelpExternalApiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7. Feedback &amp; Contact.
        /// </summary>
        internal static string HelpFeedback {
            get {
                return ResourceManager.GetString("HelpFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you found a bug, need a feature or have an idea, share it with me at the project repository..
        /// </summary>
        internal static string HelpFeedbackDescription {
            get {
                return ResourceManager.GetString("HelpFeedbackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6. Garmin and Xiaomi.
        /// </summary>
        internal static string HelpGarminAndXiaomi {
            get {
                return ResourceManager.GetString("HelpGarminAndXiaomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This application is an open source community project and I have no affiliation with Garmin or Xiaomi. You use it at your own risk. You can always check out the source code on Github..
        /// </summary>
        internal static string HelpGarminAndXiaomiDescription {
            get {
                return ResourceManager.GetString("HelpGarminAndXiaomiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2. How It works.
        /// </summary>
        internal static string HelpHowItWorks {
            get {
                return ResourceManager.GetString("HelpHowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This App pass your data, email and password directly to Garmin Cloud or via external API server. The API does not store or log anything, it&apos;s just a middleware between this App and Garmin services..
        /// </summary>
        internal static string HelpHowItWorksDescription {
            get {
                return ResourceManager.GetString("HelpHowItWorksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3. Strange results? (Like 10kg only).
        /// </summary>
        internal static string HelpStrangeResults {
            get {
                return ResourceManager.GetString("HelpStrangeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you have the Mi Body Composition Scale 2. Disable the &apos;Weight small object&apos; option in Zepp Life.
        /// </summary>
        internal static string HelpStrangeResultsDescription {
            get {
                return ResourceManager.GetString("HelpStrangeResultsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4. Results different from Zepp Life.
        /// </summary>
        internal static string HelpZeppLifeDriference {
            get {
                return ResourceManager.GetString("HelpZeppLifeDriference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please check the age/height/gender parameters - should be identical in both apps. But even then, the values may be slightly different because we do not use the exact algorithm used by Xiaomi, but an alternative open source algorithm..
        /// </summary>
        internal static string HelpZeppLifeDriferenceDescription {
            get {
                return ResourceManager.GetString("HelpZeppLifeDriferenceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ideal Weight (Kg):.
        /// </summary>
        internal static string IdealWeightKg {
            get {
                return ResourceManager.GetString("IdealWeightKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ideal Weight (Lbs):.
        /// </summary>
        internal static string IdealWeightLbs {
            get {
                return ResourceManager.GetString("IdealWeightLbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MFA Code.
        /// </summary>
        internal static string MFACode {
            get {
                return ResourceManager.GetString("MFACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mi Body Composition Scale 1 / 2.
        /// </summary>
        internal static string MiBodyCompositionScale {
            get {
                return ResourceManager.GetString("MiBodyCompositionScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mi Scale.
        /// </summary>
        internal static string MiScale {
            get {
                return ResourceManager.GetString("MiScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mi Scale Data.
        /// </summary>
        internal static string MiScaleData {
            get {
                return ResourceManager.GetString("MiScaleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mi Scale Exporter.
        /// </summary>
        internal static string MiScaleExporter {
            get {
                return ResourceManager.GetString("MiScaleExporter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mi Smart Scale.
        /// </summary>
        internal static string MiSmartScale {
            get {
                return ResourceManager.GetString("MiSmartScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Muscle mass as %.
        /// </summary>
        internal static string MuscleMassAsPercentage {
            get {
                return ResourceManager.GetString("MuscleMassAsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Muscle Mass (Kg).
        /// </summary>
        internal static string MuscleMassKg {
            get {
                return ResourceManager.GetString("MuscleMassKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Muscle Mass (Lbs).
        /// </summary>
        internal static string MuscleMassLbs {
            get {
                return ResourceManager.GetString("MuscleMassLbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Muscle Mass (%).
        /// </summary>
        internal static string MuscleMassPer {
            get {
                return ResourceManager.GetString("MuscleMassPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One click - Scan &amp; Upload.
        /// </summary>
        internal static string OneClickScanUpload {
            get {
                return ResourceManager.GetString("OneClickScanUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Help.
        /// </summary>
        internal static string OpenHelp {
            get {
                return ResourceManager.GetString("OpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission to use Bluetooth is required to scan..
        /// </summary>
        internal static string PermissionBluetoothRequired {
            get {
                return ResourceManager.GetString("PermissionBluetoothRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permission to use Location (Bluetooth) is required to scan..
        /// </summary>
        internal static string PermissionLocationRequired {
            get {
                return ResourceManager.GetString("PermissionLocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Problem.
        /// </summary>
        internal static string Problem {
            get {
                return ResourceManager.GetString("Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Protein (%):.
        /// </summary>
        internal static string ProteinPercent {
            get {
                return ResourceManager.GetString("ProteinPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset to Default.
        /// </summary>
        internal static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Response.
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scale Model.
        /// </summary>
        internal static string ScaleModel {
            get {
                return ResourceManager.GetString("ScaleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scale Settings.
        /// </summary>
        internal static string ScaleSettings {
            get {
                return ResourceManager.GetString("ScaleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scanning....
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send to Health Connect.
        /// </summary>
        internal static string SendToHealthConnect {
            get {
                return ResourceManager.GetString("SendToHealthConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide Ads Banner.
        /// </summary>
        internal static string SettingsHideAds {
            get {
                return ResourceManager.GetString("SettingsHideAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sex.
        /// </summary>
        internal static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Debug Info during scan.
        /// </summary>
        internal static string ShowDebug {
            get {
                return ResourceManager.GetString("ShowDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop Measure.
        /// </summary>
        internal static string StopMeasure {
            get {
                return ResourceManager.GetString("StopMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time of measurement.
        /// </summary>
        internal static string TimeOfMeasurement {
            get {
                return ResourceManager.GetString("TimeOfMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploaded.
        /// </summary>
        internal static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uploading....
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Upload to Garmin Cloud.
        /// </summary>
        internal static string UploadToGarminCloud {
            get {
                return ResourceManager.GetString("UploadToGarminCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use External API.
        /// </summary>
        internal static string UseExternalAPI {
            get {
                return ResourceManager.GetString("UseExternalAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Values that will not be sent to the cloud:.
        /// </summary>
        internal static string ValuesThatWillNotBeSentToTheCloud {
            get {
                return ResourceManager.GetString("ValuesThatWillNotBeSentToTheCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visceral fat.
        /// </summary>
        internal static string VisceralFat {
            get {
                return ResourceManager.GetString("VisceralFat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visit the project repository.
        /// </summary>
        internal static string VisitProjectRepository {
            get {
                return ResourceManager.GetString("VisitProjectRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Water (%).
        /// </summary>
        internal static string WaterPercent {
            get {
                return ResourceManager.GetString("WaterPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight (Kg).
        /// </summary>
        internal static string WeightKg {
            get {
                return ResourceManager.GetString("WeightKg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight (Lbs).
        /// </summary>
        internal static string WeightLbs {
            get {
                return ResourceManager.GetString("WeightLbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weight must be greater than zero..
        /// </summary>
        internal static string WeightRequiredError {
            get {
                return ResourceManager.GetString("WeightRequiredError", resourceCulture);
            }
        }
    }
}
